-- Create table to store retail transaction data
CREATE TABLE retail (
InvoiceNo TEXT,
StockCode TEXT,
Description TEXT,
Quantity INT,
InvoiceDate TIMESTAMP,
UnitPrice FLOAT,
CustomerID FLOAT,
Country TEXT
);

-- View all raw data
SELECT * FROM retail;

-- Add a unique ID column as primary key
ALTER TABLE retail
ADD COLUMN id SERIAL PRIMARY KEY;

-- Verify table after adding ID
SELECT * FROM retail;

-- Filter valid transactions (exclude returns and negative quantities)
SELECT *
FROM retail
WHERE Quantity > 0
AND InvoiceNo NOT LIKE 'C%';

-- Calculate total revenue from valid sales
SELECT SUM(Quantity * UnitPrice) AS total_revenue
FROM retail
WHERE Quantity > 0
AND InvoiceNo NOT LIKE 'C%';

-- Revenue generated by each country
SELECT Country,
SUM(Quantity * UnitPrice) AS revenue
FROM retail
WHERE Quantity > 0
AND InvoiceNo NOT LIKE 'C%'
GROUP BY Country
ORDER BY revenue DESC;

-- Top 10 customers based on revenue contribution
SELECT CustomerID,
SUM(Quantity * UnitPrice) AS revenue
FROM retail
WHERE Quantity > 0
AND InvoiceNo NOT LIKE 'C%'
AND CustomerID IS NOT NULL
GROUP BY CustomerID
ORDER BY revenue DESC
LIMIT 10;

-- Top 10 best-selling products by quantity sold
SELECT Description,
SUM(Quantity) AS total_sold
FROM retail
WHERE Quantity > 0
AND InvoiceNo NOT LIKE 'C%'
GROUP BY Description
ORDER BY total_sold DESC
LIMIT 10;

-- Monthly revenue trend over time
SELECT DATE_TRUNC('month', InvoiceDate) AS month,
SUM(Quantity * UnitPrice) AS revenue
FROM retail
WHERE Quantity > 0
AND InvoiceNo NOT LIKE 'C%'
GROUP BY month
ORDER BY month;

-- Count total number of returned transactions
SELECT COUNT(*) AS total_returns
FROM retail
WHERE InvoiceNo LIKE 'C%';

-- Identify products with highest return quantities
SELECT Description,
SUM(Quantity) AS returned_qty
FROM retail
WHERE InvoiceNo LIKE 'C%'
GROUP BY Description
ORDER BY returned_qty ASC;

-- Country-level customer count and revenue
SELECT Country,
COUNT(DISTINCT CustomerID) AS customers,
SUM(Quantity * UnitPrice) AS revenue
FROM retail
WHERE Quantity > 0
AND InvoiceNo NOT LIKE 'C%'
GROUP BY Country
ORDER BY revenue DESC;

-- Monthly revenue breakdown by country
SELECT DATE_TRUNC('month', InvoiceDate) AS month,
Country,
SUM(Quantity * UnitPrice) AS revenue
FROM retail
WHERE Quantity > 0
AND InvoiceNo NOT LIKE 'C%'
GROUP BY month, Country
ORDER BY month, revenue DESC;

-- Monthly product sales to track product performance over time
SELECT DATE_TRUNC('month', InvoiceDate) AS month,
Description,
SUM(Quantity) AS total_sold
FROM retail
WHERE Quantity > 0
AND InvoiceNo NOT LIKE 'C%'
GROUP BY month, Description
ORDER BY month, total_sold DESC;

-- Count total orders per customer
SELECT CustomerID,
COUNT(DISTINCT InvoiceNo) AS total_orders
FROM retail
WHERE Quantity > 0
AND InvoiceNo NOT LIKE 'C%'
AND CustomerID IS NOT NULL
GROUP BY CustomerID;

-- Categorize customers into one-time vs repeat buyers
SELECT
CASE
WHEN total_orders = 1 THEN 'One-time'
ELSE 'Repeat'
END AS customer_type,
COUNT(*) AS num_customers
FROM (
SELECT CustomerID,
COUNT(DISTINCT InvoiceNo) AS total_orders
FROM retail
WHERE Quantity > 0
AND InvoiceNo NOT LIKE 'C%'
AND CustomerID IS NOT NULL
GROUP BY CustomerID
) t
GROUP BY customer_type;

-- Calculate total value of each order (invoice)
SELECT InvoiceNo,
SUM(Quantity * UnitPrice) AS order_value
FROM retail
WHERE Quantity > 0
AND InvoiceNo NOT LIKE 'C%'
GROUP BY InvoiceNo;

-- Calculate average order value across all transactions
SELECT AVG(order_value) AS avg_order_value
FROM (
SELECT InvoiceNo,
SUM(Quantity * UnitPrice) AS order_value
FROM retail
WHERE Quantity > 0
AND InvoiceNo NOT LIKE 'C%'
GROUP BY InvoiceNo
) t;






